import 'element-plus/es/components/option/style/css'
import 'element-plus/es/components/option-group/style/css'
import 'element-plus/es/components/select/style/css'
import 'element-plus/es/components/loading/style/css'
import '@hl/theme-chalk/select.scss'
