import 'element-plus/es/components/loading/style/css'
import 'element-plus/es/components/progress/style/css'
import '@hl/theme-chalk/upload.scss'
import '../../preview/style/index'
import '../../icon/style/index'
